# Generated by Django 5.1.5 on 2025-03-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watched_series',
            old_name='movie_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='watched_series',
            old_name='movie_name',
            new_name='name',
        ),
    ]
