# Generated by Django 5.1.5 on 2025-03-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0002_rename_movie_image_watched_series_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='watched_later_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
